# Generated by Django 5.1.2 on 2024-11-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_extra',
            fields=[
                ('id_prod', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=30)),
                ('talla', models.CharField(max_length=15)),
                ('precio_uni', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('id_proveedor', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
