# Generated by Django 5.1.2 on 2024-11-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_provee', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('num_ruta', models.CharField(max_length=10)),
                ('cant_prod', models.IntegerField()),
                ('peso', models.FloatField()),
                ('tipo_prod', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=150)),
            ],
        ),
    ]
